name: shelter_in_place
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^3.1.0
  flutter_localizations:
    sdk: flutter
  intl:
  intl_translation:
  shared_preferences: ^0.5.6+3
  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  firebase_database: ^3.0.7
  cloud_firestore: ^0.12.9+5
  charts_flutter: ^0.9.0
  flutter_svg: ^0.17.3
  smooth_page_indicator: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - i18n/en.json
    - i18n/es.json
    - i18n/nl.json
    - -g-distanceGraphic.svg
    - logo2.png
    - logo3.png
    - wordmark3.png
  fonts:
    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-Regular.otf
        - asset: fonts/Gilroy-RegularItalic.otf
          style: italic
        - asset: fonts/Gilroy-Black.otf
          weight: 950
        - asset: fonts/Gilroy-BlackItalic.otf
          weight: 950
          style: italic
        - asset: fonts/Gilroy-Bold.otf
          weight: 700
        - asset: fonts/Gilroy-BoldItalic.otf
          weight: 700
          style: italic
        - asset: fonts/Gilroy-ExtraBold.otf
          weight: 800
        - asset: fonts/Gilroy-ExtraBoldItalic.otf
          weight: 800
          style: italic
        - asset: fonts/Gilroy-Heavy.otf
          weight: 900
        - asset: fonts/Gilroy-HeavyItalic.otf
          weight: 900
          style: italic
        - asset: fonts/Gilroy-Light.otf
          weight: 300
        - asset: fonts/Gilroy-LightItalic.otf
          weight: 300
          style: italic
        - asset: fonts/Gilroy-Medium.otf
          weight: 500
        - asset: fonts/Gilroy-MediumItalic.otf
          weight: 500
          style: italic
        - asset: fonts/Gilroy-SemiBold.otf
          weight: 600
        - asset: fonts/Gilroy-SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: fonts/Gilroy-Thin.otf
          weight: 100
        - asset: fonts/Gilroy-ThinItalic.otf
          weight: 100
          style: italic
        - asset: fonts/Gilroy-UltraLight.otf
          weight: 200
        - asset: fonts/Gilroy-UltraLightItalic.otf
          weight: 200
          style: italic
#          todo add all the font files -> done!
  uses-material-design: true
