import 'package:flutter/material.dart';
Color purple = Colors.deepPurple[200];
Color cyan = Colors.cyan[100];
Color indigo = Colors.indigo[400];
Color pink = Colors.pink[100];
Color yellow = Colors.amber[200];
Color orange = Colors.deepOrange[200];
Color teal = Colors.tealAccent[100];
Color blue = Colors.blue[200];
Color red = Colors.red[300];
Color yellow2 = Colors.yellow[300];
Color green = Colors.lightGreenAccent[100];
Color brown = Colors.brown[200];
Color backgroundGrey = Colors.grey[200];